package org.example.hello2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-05-28T19:30:54.082+08:00
 * Generated source version: 2.6.0
 * 
 */
@WebService(targetNamespace = "http://www.example.org/hello2/", name = "hello2")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Hello2 {

    @WebResult(name = "NewOperationResponse", targetNamespace = "http://www.example.org/hello2/", partName = "parameters")
    @WebMethod(operationName = "NewOperation", action = "http://www.example.org/hello2/NewOperation")
    public NewOperationResponse newOperation(
        @WebParam(partName = "parameters", name = "helloRequest", targetNamespace = "http://www.example.org/hello2/")
        HelloRequest parameters
    );
}
