
package org.example.hello2;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-05-28T19:30:54.117+08:00
 * Generated source version: 2.6.0
 * 
 */
 
public class Hello2_Hello2SOAP_Server{

    protected Hello2_Hello2SOAP_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new Hello2Impl();
        String address = "http://www.example.org/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new Hello2_Hello2SOAP_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
