
package net.bluedash.ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-05-28T19:11:22.404+08:00
 * Generated source version: 2.6.0
 * 
 */
 
public class HelloService_HelloServiceSOAP_Server{

    protected HelloService_HelloServiceSOAP_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new HelloServiceImpl();
        String address = "http://localhost:8080/ws/sayHello";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new HelloService_HelloServiceSOAP_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
