package net.bluedash.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-05-28T19:11:28.361+08:00
 * Generated source version: 2.6.0
 * 
 */
@WebService(targetNamespace = "http://bluedash.net/ws", name = "HelloService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface HelloService {

    @WebResult(name = "helloResponse", targetNamespace = "http://bluedash.net/ws", partName = "response")
    @WebMethod(action = "http://bluedash.net/ws/sayHello")
    public java.lang.String sayHello(
        @WebParam(partName = "request", name = "helloRequest", targetNamespace = "http://bluedash.net/ws")
        HelloRequest request
    );
}
