package net.bluedash.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.URL;

import javax.xml.namespace.QName;
/**
 * This class was generated by Apache CXF 2.6.0 2012-05-28T19:11:28.314+08:00
 * Generated source version: 2.6.0
 * 
 */
public final class HelloService_HelloServiceSOAP_Client {

	private static final QName SERVICE_NAME = new QName(
			"http://bluedash.net/ws", "HelloService");

	private HelloService_HelloServiceSOAP_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {

		HelloService_Service ss = new HelloService_Service((new File(
				"/Users/weli/projs/hello/src/hello.wsdl")).toURI().toURL(),
				SERVICE_NAME);

		HelloService port = ss.getHelloServiceSOAP();

		{
			System.out.println("Invoking sayHello...");
			net.bluedash.ws.HelloRequest _sayHello_request = new HelloRequest();
			_sayHello_request.setWho("world");

			java.lang.String _sayHello__return = port
					.sayHello(_sayHello_request);
			System.out.println("sayHello.result=" + _sayHello__return);

		}

		System.exit(0);
	}

}
